version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "20:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
    - 1.10.1
    - 1.9.2
  - dependency-name: pry
    versions:
    - 0.13.1
    - 0.14.0
  - dependency-name: rubocop-rspec
    versions:
    - 2.1.0
